services:
  db:
    image: postgis/postgis:17-3.5
    container_name: conflitos_agrarios_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conflitos_agrarios
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d conflitos_agrarios"]
      interval: 5s
      timeout: 5s
      retries: 5

  martin:
    image: maplibre/martin:latest
    container_name: conflitos_agrarios_martin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/conflitos_agrarios
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

